### ISSUE TITLE
[Insight] Text files should end with a newline character - in project/app/config/config_test.yml, line 21

### ISSUE THREAD

**Issue by lkochniss** [lkochniss/intent-backend#81]
**[in project/app/config/config_test.yml, line 21](https://github.com/lkochniss/intent-backend/blob/217386ba1b344146ed37ba33449368582c2f1999/project/app/config/config_test.yml#L21)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```
    disable_delivery: true

security:
    firewalls:
        backend:
            http_basic: ~
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/fb1c0bab-ea7f-4185-89c1-e80dcbfc3fe5/analyses/4)_
